SAAS-255 Package go code as action
percona-platform/get-stale-packages-action pull request #1
Opened 2020-09-15 12:16 UTC by palash25

[Ticket](https://jira.percona.com/browse/SAAS-255)

2020-09-16 09:57 UTC, palash25 commented
@AlekSi a few questions do we want vendored deps in this repo or not?

and how do I test this action? should I include a worflow in this repo that will run the action or should we merge this straightaway and try to use it in the template repo?

2020-09-16 10:18 UTC, palash25 commented
i went through the actions doc https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#example-using-a-private-action  and tried to  write this worflow that will run the `action.yml` but it failed saying "Only actions in "percona-platform" are allowed for this repository" not sure why that happened, maybe something to do with the settings of this repo

```
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test action.yml
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: get-stale-packages
        uses: ./ # Uses an action in the root directory
        id: get-stale-packages
      # Use the output from the `get-stale-packages` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
```

2020-09-17 09:22 UTC, palash25 commented
tried this in a repo of mine and it ran https://github.com/palash25/gh-action/pull/1/checks?check_run_id=1127682075

2020-09-17 10:41 UTC, AlekSi requested changes

2020-09-17 10:41 UTC, AlekSi commented on .github/CODEOWNERS
> +@AlekSi @palash25
CODEOWNERS has a different syntax, that probably will not work.

And please add line breaks everywhere where you see that red symbol

2020-09-17 10:52 UTC, palash25 commented
removed the vendor added linebreaks, can we merge this?

2020-09-17 11:13 UTC, AlekSi requested changes
Please add basic CI configuration that checks that this Go code can be compiled.
Please add usage example in README.

2020-09-17 11:13 UTC, AlekSi commented on .github/dependabot.yml
> +        directory: "/tools"
There is no /tools

2020-09-17 11:13 UTC, AlekSi commented on .github/dependabot.yml
> +      - package-ecosystem: "docker"
We don't use Docker there

2020-09-17 11:13 UTC, AlekSi commented on main.go
> +				if matchVersion(node.Version) {
Please log versions that were considered and if they were picked or not

2020-09-17 11:13 UTC, AlekSi commented on main.go
> +	fmt.Println(strings.Join(versions, ", "))
We should do the same as out other action: https://github.com/percona-platform/authed/blob/b1a92733a3b878da5230526584c97d6714bfdc34/tools/extract-image-tag/extract-image-tag.go#L55-L56

2020-09-17 13:49 UTC, palash25 commented
don't re-review yet @AlekSi I mistakenly hit the button, still need to update the README

2020-09-17 13:58 UTC, palash25 commented
added usage in the README

2020-09-17 13:58 UTC, AlekSi requested changes

2020-09-17 13:58 UTC, AlekSi commented on .github/workflows/ci.yml
> +        run: go build -v .
\n

(please configure your editor / IDE to always add them)

2020-09-17 13:58 UTC, AlekSi commented on main.go
> +					log.Printf("Stale version detected: %s", node.Version)
It is not stale there yet, only after `if` below.

2020-09-17 13:58 UTC, AlekSi commented on main.go
> +				if matchVersion(node.Version) {
Please don't forget "or not" part. Basically, log all version with yay / nay

2020-09-17 14:00 UTC, AlekSi requested changes

2020-09-17 14:00 UTC, AlekSi commented on README.md
> +      uses: echo 'The stale package versions are' $STALE_VERSIONS
Please add action there that actually removes packages. We will copy&paste that snipped

2020-09-17 14:40 UTC, AlekSi commented on README.md
> +          echo ::set-output name=length::${length}
That should be inside action.

Probably we should stick to environment variables only.

2020-09-17 14:44 UTC, palash25 commented on README.md
> +          echo ::set-output name=length::${length}
you mean calculate the length in `main.go` and set it as env var?

2020-09-17 14:46 UTC, AlekSi commented on README.md
> +          echo ::set-output name=length::${length}
Well, if we need it. But I think we can do something better. https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#operators – looks like empty string evaluates to false, so there is no real need to set length, right?

2020-09-17 15:03 UTC, palash25 commented on README.md
> +          echo ::set-output name=length::${length}
yeah looks like it, will update the usage accordingly

2020-09-17 15:49 UTC, AlekSi commented on README.md
> +          echo ::set-output name=length::${length}
But please actually make it work before requesting re-review.
https://github.com/percona-platform/authed/pull/47
https://github.com/percona-platform/authed/actions/runs/259615077

2020-09-17 15:50 UTC, AlekSi requested changes
https://github.com/percona-platform/get-stale-packages-action/pull/1#discussion_r490358730

2020-09-17 16:17 UTC, AlekSi commented on main.go
> +	}
We should use standard GITHUB_REPOSITORY instead of REPOSITORY_OWNER and REPOSITORY_NAME: https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables

2020-09-17 16:31 UTC, AlekSi commented on main.go
> +						log.Printf("Package version is stale: %s", node.ID.(string))
It logs `Package version is stale: MDE0OlBhY2thZ2VWZXJzaW9uMzcwMDg3Nw==` We probably should add Version and UpdateAt

2020-09-18 09:50 UTC, palash25 commented on main.go
> +						log.Printf("Package version is stale: %s", node.ID.(string))
Does this format looks good?

`Package version SAAS-255-Package-Get-Stale-Packages with id: MDE0OlBhY2thZ2VWZXJzaW9uMzg2NTAzMA== UpdatedAt: 2020-09-17 16:41:40 +0000 UTC is not stale`

2020-09-18 09:53 UTC, palash25 commented on README.md
> +          echo ::set-output name=length::${length}
seems to work https://github.com/percona-platform/authed/pull/47/checks?check_run_id=1133193750

2020-09-18 11:59 UTC, AlekSi commented on README.md
> +    steps:
So we will copy&paste those lines too?

2020-09-18 11:59 UTC, AlekSi commented on README.md
> +      uses: percona-platform/get-stale-packages-action@47ce28644a5c4082fdc7aa7a8898192454ff53b0
So we will use exactly the same version everywhere, even after merging this PR?

2020-09-18 12:00 UTC, AlekSi commented on README.md
> +      if: env.STALE_VERSIONS > 0
So we compare string with a number?

2020-09-18 12:01 UTC, AlekSi commented on main.go
> +	token := os.Getenv("ROBOT_TOKEN")
So we have to pass it, but don't mention in README?

Did you saw how I made it work: https://github.com/percona-platform/authed/pull/47/files ?

2020-09-18 12:07 UTC, palash25 commented on README.md
> +      if: env.STALE_VERSIONS > 0
just to keep it consistent with the change I made here to trigger a new build https://github.com/percona-platform/authed/pull/47/commits/e5879aedbe433bbc81e812b922e197bd8d18ae28#diff-b7c21c4009fb882d951121b453ec2ac9R110  I will change that back in both the PRs

2020-09-18 12:15 UTC, palash25 commented on README.md
> +    steps:
those were just to provide some context in a minimal example, I will remove that and add a better description in the README

2020-09-18 12:17 UTC, palash25 commented on README.md
> +      uses: percona-platform/get-stale-packages-action@47ce28644a5c4082fdc7aa7a8898192454ff53b0
no since we don't have a release yet, I didn't touch that, wasn't sure what version to put there, should I use v1.0.0 ?

2020-09-18 12:20 UTC, AlekSi commented on README.md
> +      uses: percona-platform/get-stale-packages-action@47ce28644a5c4082fdc7aa7a8898192454ff53b0
Any version, really. `v1.0.0` or `v0.1.0`. Dependabot will update it once we release newer versions.

2020-09-18 12:49 UTC, palash25 commented on main.go
> +	token := os.Getenv("ROBOT_TOKEN")
actually the PR diff didn't show 

```
        env:
          ROBOT_TOKEN: ${{ secrets.ROBOT_TOKEN }}
```

as a new addition for some reason and I missed it, now that I saw the individual commit I got to know that you added that

anyway added it to the usage

2020-09-20 12:40 UTC, AlekSi commented
And I'm sorry for being cranky for no good reason.

2020-09-20 12:40 UTC, AlekSi approved these changes

2020-09-20 12:40 UTC, merged